### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vardhanshorewala** [CoopHive/coophive#28]
Attempting to run the following command using the coophive.module.marker repository at commit `cc6537a0937be9133a9570bb14926443b04fc965`:

```
hive run github.com/CoopHive/coophive-module-marker:cc6537a0937be9133a9570bb14926443b04fc965 -i input=/inputs/QmRA3NWM82ZGynMbYzAgYTSXCVM14Wx1RZ8fKP42G6gjgj -i url=https://gateway.lighthouse.storage/ipfs/QmRA3NWM82ZGynMbYzAgYTSXCVM14Wx1RZ8fKP42G6gjgj
```

However, the command resulted in an error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x104d874e4]

goroutine 1 [running]:
text/template.(*Template).init(...)
	/home/circleci/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.7.linux-amd64/src/text/template/template.go:71
text/template.(*Template).Funcs(0x0, 0x140005742d8?)
	/home/circleci/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.7.linux-amd64/src/text/template/template.go:178 +0x34
github.com/CoopHive/coophive/pkg/module.LoadModule({{0x0, 0x0}, {0x140004690c0, 0x32}, {0x16b313754, 0x28}, {0x10555e00c, 0x10}}, 0x30?)
	/home/circleci/project/pkg/module/utils.go:222 +0x290
github.com/CoopHive/coophive/pkg/jobcreator.getJobOfferFromOptions({{{0x0, 0x0}, {0x140004690c0, 0x32}, {0x16b313754, 0x28}, {0x10555e00c, 0x10}}, {0x0, 0x0, ...}, ...}, ...)
	/home/circleci/project/pkg/jobcreator/utils.go:16 +0x6c
github.com/CoopHive/coophive/pkg/jobcreator.(*JobCreator).GetJobOfferFromOptions(_, {{{0x0, 0x0}, {0x140004690c0, 0x32}, {0x16b313754, 0x28}, {0x10555e00c, 0x10}}, {0x0, ...}, ...})
	/home/circleci/project/pkg/jobcreator/jobcreator.go:69 +0xdc
github.com/CoopHive/coophive/pkg/jobcreator.RunJob(_, {{0x0}, {{{0x0, 0x0}, {0x140004690c0, 0x32}, {0x16b313754, 0x28}, {0x10555e00c, 0x10}}, ...}, ...}, ...)
	/home/circleci/project/pkg/jobcreator/run.go:40 +0x1ac
github.com/CoopHive/coophive/cmd/hive.runJob(_, {{0x0}, {{{0x0, 0x0}, {0x140004690c0, 0x32}, {0x16b313754, 0x28}, {0x10555e00c, 0x10}}, ...}, ...})
	/home/circleci/project/cmd/hive/run.go:80 +0x3c0
github.com/CoopHive/coophive/cmd/hive.newRunCmd.func1(0x14000536200?, {0x1400046ea50?, 0x4?, 0x10554f449?})
	/home/circleci/project/cmd/hive/run.go:33 +0xdc
github.com/spf13/cobra.(*Command).execute(0x1400050f200, {0x1400046ea00, 0x5, 0x5})
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x1400050e900)
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/CoopHive/coophive/cmd/hive.Execute()
	/home/circleci/project/cmd/hive/root.go:35 +0xb0
main.main()
	/home/circleci/project/main.go:8 +0x1c
```

**Comment by lukemarsden** [comment]
relates to https://github.com/CoopHive/coophive/issues/17
